 apt-get -y source openssl
 apt-get -y source #bluetooth
 apt-get -y source blueproximity
 apt-get -y source btscanner
 apt-get -y source #Uncomment_these_lines_if_you_want_a_fully-fledged_IDE.
 apt-get -y source #anjuta
 apt-get -y source #anjuta-common
 apt-get -y source #anjuta-extras
 apt-get -y source hibernate
 apt-get -y source vbetool
 apt-get -y source uswsusp
 apt-get -y source asciidoc
 apt-get -y source autoconf
 apt-get -y source automake
 apt-get -y source autotools-dev
 apt-get -y source -y build-essential
 apt-get -y source cmake
 apt-get -y source cgdb
 apt-get -y source debhelper
 apt-get -y source devhelp-common
 apt-get -y source devscripts
 apt-get -y source dh-make
 apt-get -y source doc-base
 apt-get -y source docbook-xml
 apt-get -y source docutils-common
 apt-get -y source docutils-doc
 apt-get -y source doxygen
 apt-get -y source dpkg-dev
 apt-get -y source gcc
 apt-get -y source g++
 apt-get -y source medit
 apt-get -y source git
 apt-get -y source globus-simple-ca
 apt-get -y source gperf
 apt-get -y source intltool
 apt-get -y source libasound2-dev
 apt-get -y source libboost-dev
 apt-get -y source libboost-chrono-dev
 apt-get -y source libboost-filesystem-dev
 apt-get -y source libboost-program-options-dev
 apt-get -y source libboost-system-dev
 apt-get -y source libboost-test-dev
 apt-get -y source libboost-thread-dev
 apt-get -y source libc6-dev
 apt-get -y source libc6-dbg
 apt-get -y source libcairo2-dev
 apt-get -y source libcurl4-openssl-dev
 apt-get -y source libdb-dev
 apt-get -y source libev-dev
 apt-get -y source libevent-dev
 apt-get -y source libgtk2.0-dev
 apt-get -y source libimlib2-dev
 apt-get -y source libltdl-dev
 apt-get -y source libtool
 apt-get -y source liblua5.1-dev
 apt-get -y source liblua5.2-dev
 apt-get -y source libnotify-dev
 apt-get -y source libgcrypt11-dev
 apt-get -y source libgcrypt20-dev
 apt-get -y source libgpg-error-dev
 apt-get -y source libotr5
 apt-get -y source libotr5-bin
 apt-get -y source libotr5-dev
 apt-get -y source libpango1.0-dev
 apt-get -y source libssl-dev
 apt-get -y source libstartup-notification0-dev
 apt-get -y source libsodium-dev
 apt-get -y source libsodium-dbg
 apt-get -y source libstdc++-4.8-dev
 apt-get -y source #libtox-dev
 apt-get -y source #libtoxcore0
 apt-get -y source #libtoxcore-dev
 apt-get -y source #libtoxav0
 apt-get -y source #libtoxav-dev
 apt-get -y source #libtoxencryptsave0
 apt-get -y source #libtoxencryptsave-dev
 apt-get -y source #libtoxdns0
 apt-get -y source #libtoxdns-dev
 apt-get -y source libx11-xcb-dev
 apt-get -y source libxcb1-dev
 apt-get -y source libxcb-image0-dev
 apt-get -y source libxcb-icccm4-dev
 apt-get -y source libxcb-keysyms1-dev
 apt-get -y source libxcb-randr0-dev
 apt-get -y source libxcb-shape0-dev
 apt-get -y source libxcb-util0-dev
 apt-get -y source libxcb-xinerama0-dev
 apt-get -y source libxcb-xtest0-dev
 apt-get -y source libxcursor-dev
 apt-get -y source libxdg-basedir-dev
 apt-get -y source libxdo-dev
 apt-get -y source libxt-dev
 apt-get -y source libiw-dev
 apt-get -y source libidl-dev
 apt-get -y source mesa-common-dev
 apt-get -y source autoconf2.13
 apt-get -y source yasm
 apt-get -y source python-dev
 apt-get -y source libgstreamer0.10-dev
 apt-get -y source libgstreamer-plugins-base0.10-dev
 apt-get -y source libpulse-dev
 apt-get -y source lintian
 apt-get -y source lua5.1
 apt-get -y source lua5.2
 apt-get -y source luadoc
 apt-get -y source lua-ldoc
 apt-get -y source make
 apt-get -y source mercurial
 apt-get -y source moreutils
 apt-get -y source nodejs
 apt-get -y source nodejs-legacy
 apt-get -y source p-y builder
 apt-get -y source python-rope
 apt-get -y source tig
 apt-get -y source valac
 apt-get -y source valgrind
 apt-get -y source xmlto
 apt-get -y source zip
 apt-get -y source #anoncoind
 apt-get -y source #bitcoind
 apt-get -y source #litecoind
 apt-get -y source #namecoin
 apt-get -y source alsa-base
 apt-get -y source alsa-tools
 apt-get -y source alsa-utils
 apt-get -y source alsa-oss
 apt-get -y source alsamixergui
 apt-get -y source apt-transport-https
 apt-get -y source apt-transport-tor
 apt-get -y source apt-p2p
 apt-get -y source dctrl-tools
 apt-get -y source debconf
 apt-get -y source debconf-i18n
 apt-get -y source debhelper
 apt-get -y source debian-archive-keyring
 apt-get -y source debian-faq
 apt-get -y source debian-keyring
 apt-get -y source debianutils
 apt-get -y source debootstrap
 apt-get -y source debsecan
 apt-get -y source debian-security-support
 apt-get -y source doc-debian
 apt-get -y source dpkg
 apt-get -y source dpkg-dev
 apt-get -y source dpkg-sig
 apt-get -y source gom
 apt-get -y source libalsaplayer0
 apt-get -y source openrc
 apt-get -y source #systemd-shim
 apt-get -y source #install_this_for_compatibility_with_systemd_where_necessary
 apt-get -y source awesome
 apt-get -y source awesome-extra
 apt-get -y source #awesome-lightdm-session
 apt-get -y source compton
 apt-get -y source conky-std
 apt-get -y source dialog
 apt-get -y source #network-manager
 apt-get -y source #modem-manager
 apt-get -y source mc
 apt-get -y source lightdm
 apt-get -y source lightdm-vala
 apt-get -y source lightdm-gtk-greeter
 apt-get -y source pcmanfm
 apt-get -y source #svirfneblin-panel
 apt-get -y source #Right_now_these_are_just_included_in_etc/skel
 apt-get -y source #svirfneblin-*
 apt-get -y source #Right_now_these_are_just_included_in_etc/skel
 apt-get -y source terminator
 apt-get -y source x11-apps
 apt-get -y source #xcalc
 apt-get -y source wcalc
 apt-get -y source xterm
 apt-get -y source #xdialog
 apt-get -y source #Uncomment_these_if_you_want_to_use_a_GTK_Based_Office_Suite.
 apt-get -y source #abiword
 apt-get -y source #abiword-common
 apt-get -y source #abiword-plugin-grammar
 apt-get -y source #abiword-plugin-mathview
 apt-get -y source #caca-utils
 apt-get -y source #dia
 apt-get -y source #dia-common
 apt-get -y source #dia-libs
 apt-get -y source #dia-shapes
 apt-get -y source #gnumeric
 apt-get -y source #gnumeric-common
 apt-get -y source #gnumeric-doc
 apt-get -y source imagemagick
 apt-get -y source imagemagick-6.q16
 apt-get -y source imagemagick-common
 apt-get -y source markdown
 apt-get -y source pinta
 apt-get -y source hydra
 apt-get -y source john
 apt-get -y source sqlmap
 apt-get -y source ophcrack
 apt-get -y source sslscan
 apt-get -y source sslsniff
 apt-get -y source sslstrip
 apt-get -y source thc-ipv6
 apt-get -y source wireshark
 apt-get -y source yersinia
 apt-get -y source fdroidserver
 apt-get -y source crawl-common
 apt-get -y source crawl-tiles
 apt-get -y source crawl-tiles-data
 apt-get -y source freeciv-client-sdl
 apt-get -y source wesnoth
 apt-get -y source apparmor
 apt-get -y source apparmor-docs
 apt-get -y source apparmor-profiles
 apt-get -y source apparmor-utils
 apt-get -y source ferm
 apt-get -y source fireblock
 apt-get -y source hidblock
 apt-get -y source nufw
 apt-get -y source rkhunter
 apt-get -y source i2p
 apt-get -y source i2p-keyring
 apt-get -y source i2p-router
 apt-get -y source killyourtv-keyring
 apt-get -y source lynx-cur
 apt-get -y source ncftp
 apt-get -y source uzbl
 apt-get -y source xombrero
 apt-get -y source libreoffice-l10n-it
 apt-get -y source live-boot
 apt-get -y source live-boot-doc
 apt-get -y source live--y build
 apt-get -y source live-config
 apt-get -y source live-config-doc
 apt-get -y source live-config-sysvinit
 apt-get -y source live-manual-html
 apt-get -y source cmus
 apt-get -y source imagemagick
 apt-get -y source quodlibet
 apt-get -y source vlc
 apt-get -y source alfred
 apt-get -y source batctl
 apt-get -y source curl
 apt-get -y source horst
 apt-get -y source iftop
 apt-get -y source iptraf-ng
 apt-get -y source #joker
 apt-get -y source netcat
 apt-get -y source nmap
 apt-get -y source #rtorrent
 apt-get -y source sntop
 apt-get -y source wget
 apt-get -y source youtube-dl
 apt-get -y source apg
 apt-get -y source bleachbit
 apt-get -y source blueproximity
 apt-get -y source gnupg
 apt-get -y source gnupg-agent
 apt-get -y source gnupg2
 apt-get -y source macchanger
 apt-get -y source mat
 apt-get -y source #parcimonie
 apt-get -y source secure-delete
 apt-get -y source alpine
 apt-get -y source irssi
 apt-get -y source mumble
 apt-get -y source mutt
 apt-get -y source profanity
 apt-get -y source toxic
 apt-get -y source twidge
 apt-get -y source #twister
 apt-get -y source #tox-bootstrapd
 apt-get -y source bumblebee
 apt-get -y source firmware-linux-free
 apt-get -y source laptop-mode-tools
 apt-get -y source linux-image-amd64
 apt-get -y source primus
 apt-get -y source 
 apt-get -y source syslinux-common
 apt-get -y source syslinux-efi
 apt-get -y source user-setup
 apt-get -y source deb.torproject.org-keyring
 apt-get -y source privoxy
 apt-get -y source tor
 apt-get -y source tor-arm
 apt-get -y source tor-geoipdb
 apt-get -y source torsocks
 apt-get -y source lshw
 apt-get -y source htop
 apt-get -y source usbutils
 apt-get -y source aircrack-ng
 apt-get -y source reaver
 apt-get -y source wifite
